package montes.gutierrez.borja.TPV.vistas.principalFrame;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;
import montes.gutierrez.borja.TPV.vistas.clientes.PanelAltaCliente;
import montes.gutierrez.borja.TPV.vistas.clientes.PanelBajaCliente;
import montes.gutierrez.borja.TPV.vistas.clientes.PanelEditarCliente;
import montes.gutierrez.borja.TPV.vistas.clientes.PanelListarCliente;
import montes.gutierrez.borja.TPV.vistas.productos.PanelAltaProducto;
import montes.gutierrez.borja.TPV.vistas.productos.PanelBajaProducto;
import montes.gutierrez.borja.TPV.vistas.productos.PanelEditarProducto;
import montes.gutierrez.borja.TPV.vistas.productos.PanelListarProducto;
import montes.gutierrez.borja.TPV.vistas.tpv.Panel_TPV;
import montes.gutierrez.borja.TPV.vistas.vendedor.PanelAltaVendedor;
import montes.gutierrez.borja.TPV.vistas.vendedor.PanelBajaVendedor;
import montes.gutierrez.borja.TPV.vistas.vendedor.PanelEditarVendedor;
import montes.gutierrez.borja.TPV.vistas.vendedor.PanelListarVendedor;

/**
 * Clase que define la ventana principal de la aplicación.
 *
 * @author Borja Montes Gutiérrez
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Constructor por defecto que configura el JFrame.
     */
    public PrincipalFrame() {
        setLocationRelativeTo(null);
        Dimension frameDimension = new Dimension(770, 700);
        setSize(frameDimension);
        setPreferredSize(frameDimension);
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * Método para cargar el panel contenedor
     *
     * @param panel JPanel contenedor con las distintas vistas.
     */
    private void cargaPanel(JPanel panel) {
        panelContenedor.removeAll();
        panelContenedor.setLayout(new BorderLayout());
        panelContenedor.add(panel);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTPV = new javax.swing.JMenu();
        menuItemTPV = new javax.swing.JMenuItem();
        jMenuClientes = new javax.swing.JMenu();
        menuItemAltaClientes = new javax.swing.JMenuItem();
        menuItemEditarClientes = new javax.swing.JMenuItem();
        jmenuItemBajaClientes = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        jMenuProductos = new javax.swing.JMenu();
        menuItemAltaProductos = new javax.swing.JMenuItem();
        menuItemEditarProductos = new javax.swing.JMenuItem();
        menuItemBajaProductos = new javax.swing.JMenuItem();
        menuItemListarProductos = new javax.swing.JMenuItem();
        jMenuVendedores = new javax.swing.JMenu();
        menuItemAltaVendedores = new javax.swing.JMenuItem();
        menuItemEditarVendedores = new javax.swing.JMenuItem();
        jmenuItemBajaVendedores = new javax.swing.JMenuItem();
        menuItemListarVendedores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelContenedor.setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/montes/gutierrez/borja/TPV/imagenes/portada.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        panelContenedor.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelContenedor, java.awt.BorderLayout.CENTER);

        jMenuTPV.setText("TPV");

        menuItemTPV.setText("Inicio TPV");
        menuItemTPV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemTPVActionPerformed(evt);
            }
        });
        jMenuTPV.add(menuItemTPV);

        jMenuBar1.add(jMenuTPV);

        jMenuClientes.setText("Clientes");

        menuItemAltaClientes.setText("Alta Cliente");
        menuItemAltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(menuItemAltaClientes);

        menuItemEditarClientes.setText("Editar Cliente");
        menuItemEditarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(menuItemEditarClientes);

        jmenuItemBajaClientes.setText("Baja Cliente");
        jmenuItemBajaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItemBajaClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(jmenuItemBajaClientes);

        menuItemListarClientes.setText("Listar Cliente");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        jMenuClientes.add(menuItemListarClientes);

        jMenuBar1.add(jMenuClientes);

        jMenuProductos.setText("Productos");

        menuItemAltaProductos.setText("Alta Producto");
        menuItemAltaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(menuItemAltaProductos);

        menuItemEditarProductos.setText("Editar Producto");
        menuItemEditarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(menuItemEditarProductos);

        menuItemBajaProductos.setText("Baja Producto");
        menuItemBajaProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBajaProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(menuItemBajaProductos);

        menuItemListarProductos.setText("Listar Productos");
        menuItemListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarProductosActionPerformed(evt);
            }
        });
        jMenuProductos.add(menuItemListarProductos);

        jMenuBar1.add(jMenuProductos);

        jMenuVendedores.setText("Vendedores");

        menuItemAltaVendedores.setText("Alta Vendedor");
        menuItemAltaVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAltaVendedoresActionPerformed(evt);
            }
        });
        jMenuVendedores.add(menuItemAltaVendedores);

        menuItemEditarVendedores.setText("Editar Vendedor");
        menuItemEditarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEditarVendedoresActionPerformed(evt);
            }
        });
        jMenuVendedores.add(menuItemEditarVendedores);

        jmenuItemBajaVendedores.setText("Baja Vendedor");
        jmenuItemBajaVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItemBajaVendedoresActionPerformed(evt);
            }
        });
        jMenuVendedores.add(jmenuItemBajaVendedores);

        menuItemListarVendedores.setText("Listar Vendedores");
        menuItemListarVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarVendedoresActionPerformed(evt);
            }
        });
        jMenuVendedores.add(menuItemListarVendedores);

        jMenuBar1.add(jMenuVendedores);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemAltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaClientesActionPerformed
        try {
            cargaPanel(new PanelAltaCliente(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAltaClientesActionPerformed

    private void menuItemEditarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarClientesActionPerformed
        cargaPanel(new PanelEditarCliente(this));
    }//GEN-LAST:event_menuItemEditarClientesActionPerformed

    private void jmenuItemBajaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItemBajaClientesActionPerformed
        cargaPanel(new PanelBajaCliente(this));
    }//GEN-LAST:event_jmenuItemBajaClientesActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        try {
            cargaPanel(new PanelListarCliente(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuItemEditarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarProductosActionPerformed

        cargaPanel(new PanelEditarProducto(this));

    }//GEN-LAST:event_menuItemEditarProductosActionPerformed

    private void menuItemAltaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaProductosActionPerformed
        try {
            cargaPanel(new PanelAltaProducto(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAltaProductosActionPerformed

    private void menuItemBajaProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBajaProductosActionPerformed
        cargaPanel(new PanelBajaProducto(this));
    }//GEN-LAST:event_menuItemBajaProductosActionPerformed

    private void menuItemListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarProductosActionPerformed
        try {
            cargaPanel(new PanelListarProducto(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListarProductosActionPerformed

    private void menuItemTPVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemTPVActionPerformed
        cargaPanel(new Panel_TPV(this));
    }//GEN-LAST:event_menuItemTPVActionPerformed

    private void menuItemAltaVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAltaVendedoresActionPerformed
        try {
            cargaPanel(new PanelAltaVendedor(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemAltaVendedoresActionPerformed

    private void menuItemEditarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEditarVendedoresActionPerformed
        cargaPanel(new PanelEditarVendedor(this));
    }//GEN-LAST:event_menuItemEditarVendedoresActionPerformed

    private void jmenuItemBajaVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItemBajaVendedoresActionPerformed
      cargaPanel(new PanelBajaVendedor(this));
    }//GEN-LAST:event_jmenuItemBajaVendedoresActionPerformed

    private void menuItemListarVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarVendedoresActionPerformed
        try {
            cargaPanel(new PanelListarVendedor(this));
        } catch (SQLException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(PrincipalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemListarVendedoresActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClientes;
    private javax.swing.JMenu jMenuProductos;
    private javax.swing.JMenu jMenuTPV;
    private javax.swing.JMenu jMenuVendedores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jmenuItemBajaClientes;
    private javax.swing.JMenuItem jmenuItemBajaVendedores;
    private javax.swing.JMenuItem menuItemAltaClientes;
    private javax.swing.JMenuItem menuItemAltaProductos;
    private javax.swing.JMenuItem menuItemAltaVendedores;
    private javax.swing.JMenuItem menuItemBajaProductos;
    private javax.swing.JMenuItem menuItemEditarClientes;
    private javax.swing.JMenuItem menuItemEditarProductos;
    private javax.swing.JMenuItem menuItemEditarVendedores;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarProductos;
    private javax.swing.JMenuItem menuItemListarVendedores;
    private javax.swing.JMenuItem menuItemTPV;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
