package montes.gutierrez.borja.TPV.vistas.vendedor;

import montes.gutierrez.borja.TPV.vistas.principalFrame.PrincipalFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import montes.gutierrez.borja.TPV.acciones.vendedor.AltaVendedores;

/**
 * Clase que define el panel para introducir nuevos vendedores.
 *
 * @author Borja Montes Gutiérrez
 */
public class PanelAltaVendedor extends javax.swing.JPanel {

    /**
     * Variables
     */
    private AltaVendedores altaVendedores;
    private PrincipalFrame frame;

    /**
     * Constructor por defecto.
     *
     * @param frame PrincipalFrame donde se va a dibujar el panel de Alta
     * vendedores.
     *
     * @throws SQLException Excepción lanzada por posibles fallos en la
     * sentencia o servidor.
     * @throws InstantiationException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws IllegalAccessException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws ClassNotFoundException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     */
    public PanelAltaVendedor(PrincipalFrame frame) throws SQLException,
            InstantiationException, IllegalAccessException,
            ClassNotFoundException {
        initComponents();
        altaVendedores = new AltaVendedores(this);
    }

    /**
     * Método para resetear los textos de los campos.
     */
    private void reset() {
        txtName.setText("");
        txtFirstSurname.setText("");
        txtSecondSurname.setText("");
    }

    /**
     * Getter del PrincipalFrame.
     *
     * @return frame principal.
     */
    public PrincipalFrame getFrame() {
        return frame;
    }

    /**
     * Setter del PrincipalFrame.
     *
     * @param frame PrincipalFrame.
     */
    public void setFrame(PrincipalFrame frame) {
        this.frame = frame;
    }

    /**
     * Getter del JTextField del primer apellido.
     *
     * @return txtFirstSurname.
     */
    public JTextField getTxtFirstSurname() {
        return txtFirstSurname;
    }

    /**
     * Setter del JTextField del primer apellido.
     *
     * @param txtFirstSurname String.
     */
    public void setTxtFirstSurname(JTextField txtFirstSurname) {
        this.txtFirstSurname = txtFirstSurname;
    }

    /**
     * Getter del JTextField del nombre.
     *
     * @return txtName.
     */
    public JTextField getTxtName() {
        return txtName;
    }

    /**
     * Setter del JTextField del nombre.
     *
     * @param txtName String.
     */
    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    /**
     * Getter del JTextField del segundo apellido.
     *
     * @return txtSecondSurname.
     */
    public JTextField getTxtSecondSurname() {
        return txtSecondSurname;
    }

    /**
     * Setter del JTextField del segundo apellido.
     *
     * @param txtSecondSurname String.
     */
    public void setTxtSecondSurname(JTextField txtSecondSurname) {
        this.txtSecondSurname = txtSecondSurname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbfirstSurname = new javax.swing.JLabel();
        txtFirstSurname = new javax.swing.JTextField();
        lbsecondSurname = new javax.swing.JLabel();
        txtSecondSurname = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Alta Vendedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(500, 400));

        lbName.setText("Nombre:");

        lbfirstSurname.setText("Primer Apellido:");

        lbsecondSurname.setText("Segundo Apellido:");

        btnSave.setText("Guardar");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSave)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnSave)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Panel Alta Vendedor");
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if (!txtName.getText().trim().isEmpty()
                && !txtFirstSurname.getText().trim().isEmpty()
                && !txtSecondSurname.getText().trim().isEmpty()) {

            altaVendedores.save();
            reset();
            JOptionPane.showMessageDialog(this, "Vendedor guardado");
        } else {
            JOptionPane.showMessageDialog(this, "Datos del vendedor incompletos");
        }
    }//GEN-LAST:event_btnSaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbfirstSurname;
    private javax.swing.JLabel lbsecondSurname;
    private javax.swing.JTextField txtFirstSurname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSecondSurname;
    // End of variables declaration//GEN-END:variables
}
