package montes.gutierrez.borja.TPV.vistas.vendedor;

import montes.gutierrez.borja.TPV.vistas.principalFrame.PrincipalFrame;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import montes.gutierrez.borja.TPV.acciones.vendedor.EditarVendedores;
import montes.gutierrez.borja.TPV.model.Vendedor;

/**
 * Clase que define el panel para editar vendedores.
 *
 * @author Borja Montes Gutiérrez
 */
public class PanelEditarVendedor extends javax.swing.JPanel {

    /**
     * Variables
     */
    private EditarVendedores editarVendedores;

    /**
     * Constructor por defecto.
     *
     * @param frame PrincipalFrame donde se va a dibujar el panel de editar
     * vendedores.
     */
    public PanelEditarVendedor(PrincipalFrame frame) {
        initComponents();
        editarVendedores = new EditarVendedores(this);
        editarVendedores.cargar();
    }

    /**
     * Método para resetear los textos de los campos.
     */
    private void reset() {
        txtName.setText("");
        txtFirstSurname.setText("");
        txtSecondSurname.setText("");
    }

    /**
     * Getter del JComboBox con los vendedores.
     *
     * @return cmbVendedores.
     */
    public JComboBox getCmbClientes() {
        return cmbVendedores;
    }

    /**
     * Getter del JTextField del id del vendedor.
     *
     * @return txtIdSeller.
     */
    public JTextField getTxtIdClient() {
        return txtIdSeller;
    }

    /**
     * Getter del JTextField del primer apellido del vendedor.
     *
     * @return txtFirstSurname.
     */
    public JTextField getTxtFirstSurname() {
        return txtFirstSurname;
    }

    /**
     * Getter del JTextField del nombre del vendedor.
     *
     * @return txtFirstSurname.
     */
    public JTextField getTxtName() {
        return txtName;
    }

    /**
     * Getter del JTextField del segundo apellido del vendedor.
     *
     * @return txtSecondSurname.
     */
    public JTextField getTxtSecondSurname() {
        return txtSecondSurname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbfirstSurname = new javax.swing.JLabel();
        txtFirstSurname = new javax.swing.JTextField();
        lbsecondSurname = new javax.swing.JLabel();
        txtSecondSurname = new javax.swing.JTextField();
        cmbVendedores = new javax.swing.JComboBox<>();
        lbseleccion = new javax.swing.JLabel();
        lbIdSeller = new javax.swing.JLabel();
        txtIdSeller = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Editar Vendedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(500, 400));

        lbName.setText("Nombre:");

        lbfirstSurname.setText("Primer Apellido:");

        lbsecondSurname.setText("Segundo Apellido:");

        cmbVendedores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbVendedoresItemStateChanged(evt);
            }
        });

        lbseleccion.setText("Seleccione vendedor:");

        lbIdSeller.setText("Id:");

        txtIdSeller.setEditable(false);

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(313, 313, 313)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIdSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbVendedores, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdSeller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbIdSeller, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnUpdate)
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVendedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbVendedoresItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Vendedor vendedor = (Vendedor) cmbVendedores.getSelectedItem();
            txtIdSeller.setText("" + vendedor.getIdSeller());
            txtName.setText(vendedor.getNameSeller());
            txtFirstSurname.setText(vendedor.getFirstSurname());
            txtSecondSurname.setText(vendedor.getSecondSurname());
        }
    }//GEN-LAST:event_cmbVendedoresItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        editarVendedores.update();
        reset();
        JOptionPane.showMessageDialog(this, "Vendedor editado");
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbVendedores;
    private javax.swing.JLabel lbIdSeller;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbfirstSurname;
    private javax.swing.JLabel lbsecondSurname;
    private javax.swing.JLabel lbseleccion;
    private javax.swing.JTextField txtFirstSurname;
    private javax.swing.JTextField txtIdSeller;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSecondSurname;
    // End of variables declaration//GEN-END:variables
}
