package montes.gutierrez.borja.TPV.vistas.clientes;

import montes.gutierrez.borja.TPV.vistas.principalFrame.PrincipalFrame;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import montes.gutierrez.borja.TPV.acciones.clientes.AltaClientes;

/**
 * Clase que define el panel para introducir nuevos clientes.
 *
 * @author Borja Montes Gutiérrez
 */
public class PanelAltaCliente extends javax.swing.JPanel {

    /**
     * Variables
     */
    private AltaClientes altaClientes;
    private PrincipalFrame frame;

    /**
     * Constructor por defecto.
     *
     * @param frame PrincipalFrame donde se va a dibujar el panel de Alta
     * Clientes.
     * @throws SQLException Excepción lanzada por posibles fallos en la
     * sentencia o servidor.
     * @throws InstantiationException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws IllegalAccessException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws ClassNotFoundException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     */
    public PanelAltaCliente(PrincipalFrame frame) throws SQLException,
            InstantiationException, IllegalAccessException,
            ClassNotFoundException {
        initComponents();
        altaClientes = new AltaClientes(this);
    }

    /**
     * Método para resetear los textos de los campos.
     */
    private void reset() {
        txtName.setText("");
        txtFirstSurname.setText("");
        txtSecondSurname.setText("");
        txtDNI.setText("");
        txtAddress.setText("");
        txtPhoneNumber.setText("");
    }

    /**
     * Getter del PrincipalFrame.
     *
     * @return frame principal.
     */
    public PrincipalFrame getFrame() {
        return frame;
    }

    /**
     * Setter del PrincipalFrame.
     *
     * @param frame PrincipalFrame.
     */
    public void setFrame(PrincipalFrame frame) {
        this.frame = frame;
    }

    /**
     * Getter del JTextField de la direccion.
     *
     * @return txtAddress.
     */
    public JTextField getTxtAddress() {
        return txtAddress;
    }

    /**
     * Setter del JTextField de la direccion.
     *
     * @param txtAddress String.
     */
    public void setTxtAddress(JTextField txtAddress) {
        this.txtAddress = txtAddress;
    }

    /**
     * Getter del JTextField del DNI.
     *
     * @return txtDNI.
     */
    public JTextField getTxtDNI() {
        return txtDNI;
    }

    /**
     * Setter del JTextField del DNI.
     *
     * @param txtDNI String.
     */
    public void setTxtDNI(JTextField txtDNI) {
        this.txtDNI = txtDNI;
    }

    /**
     * Getter del JTextField del primer apellido.
     *
     * @return txtFirstSurname.
     */
    public JTextField getTxtFirstSurname() {
        return txtFirstSurname;
    }

    /**
     * Setter del JTextField del primer apellido.
     *
     * @param txtFirstSurname String.
     */
    public void setTxtFirstSurname(JTextField txtFirstSurname) {
        this.txtFirstSurname = txtFirstSurname;
    }

    /**
     * Getter del JTextField del nombre.
     *
     * @return txtName.
     */
    public JTextField getTxtName() {
        return txtName;
    }

    /**
     * Setter del JTextField del nombre.
     *
     * @param txtName String.
     */
    public void setTxtName(JTextField txtName) {
        this.txtName = txtName;
    }

    /**
     * Getter del JTextField del número de teléfono.
     *
     * @return txtPhoneNumber.
     */
    public JTextField getTxtPhoneNumber() {
        return txtPhoneNumber;
    }

    /**
     * Setter del JTextField del número de teléfono.
     *
     * @param txtPhoneNumber String.
     */
    public void setTxtPhoneNumber(JTextField txtPhoneNumber) {
        this.txtPhoneNumber = txtPhoneNumber;
    }

    /**
     * Getter del JTextField del segundo apellido.
     *
     * @return txtSecondSurname.
     */
    public JTextField getTxtSecondSurname() {
        return txtSecondSurname;
    }

    /**
     * Setter del JTextField del segundo apellido.
     *
     * @param txtSecondSurname String.
     */
    public void setTxtSecondSurname(JTextField txtSecondSurname) {
        this.txtSecondSurname = txtSecondSurname;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbfirstSurname = new javax.swing.JLabel();
        txtFirstSurname = new javax.swing.JTextField();
        lbsecondSurname = new javax.swing.JLabel();
        txtSecondSurname = new javax.swing.JTextField();
        lbDNI = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lbAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lbphoneNumber = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Alta Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(500, 400));

        lbName.setText("Nombre:");

        lbfirstSurname.setText("Primer Apellido:");

        lbsecondSurname.setText("Segundo Apellido:");

        lbDNI.setText("DNI:");

        lbAddress.setText("Dirección:");

        lbphoneNumber.setText("Teléfono:");

        btnSave.setText("Guardar");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnSave)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbfirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbsecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnSave)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        if (!txtName.getText().trim().isEmpty()
                && !txtFirstSurname.getText().trim().isEmpty()
                && !txtSecondSurname.getText().trim().isEmpty()) {

            altaClientes.save();
            reset();
            JOptionPane.showMessageDialog(this, "Cliente guardado");
        } else {
            JOptionPane.showMessageDialog(this, "Datos del cliente incompletos");
        }
    }//GEN-LAST:event_btnSaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbAddress;
    private javax.swing.JLabel lbDNI;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbfirstSurname;
    private javax.swing.JLabel lbphoneNumber;
    private javax.swing.JLabel lbsecondSurname;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtFirstSurname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSecondSurname;
    // End of variables declaration//GEN-END:variables
}
