package montes.gutierrez.borja.TPV.vistas.productos;

import montes.gutierrez.borja.TPV.vistas.principalFrame.PrincipalFrame;
import java.sql.SQLException;
import javax.swing.JTable;
import montes.gutierrez.borja.TPV.acciones.productos.ListarProductos;

/**
 * Clase que define el panel para el listado de productos.
 *
 * @author Borja Montes Gutiérrez
 */
public class PanelListarProducto extends javax.swing.JPanel {

    /**
     * Variables
     */
    private ListarProductos listarProductos;
    private PrincipalFrame frame;

    /**
     * Constructor por defecto que inicializa los valores.
     *
     * @param frame PrincipalFrame donde se va a dibujar el panel de listar
     * productos.
     * @throws SQLException Excepción lanzada por posibles fallos en la
     * sentencia o servidor.
     * @throws InstantiationException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws IllegalAccessException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     * @throws ClassNotFoundException Excepción lanzada por posibles fallos en
     * la sentencia o servidor.
     */
    public PanelListarProducto(PrincipalFrame frame) throws SQLException, InstantiationException, IllegalAccessException, ClassNotFoundException {
        this.listarProductos = new ListarProductos(this);
        this.frame = frame;
        initComponents();
        listarProductos.listarProducto();
    }

    /**
     * Getter del JTable con los productos.
     *
     * @return jTableProducts.
     */
    public JTable getjTableProducts() {
        return jTableProducts;
    }

    /**
     * Setter del JTable con los productos.
     *
     * @param jTableProducts JTable.
     */
    public void setjTableProducts(JTable jTableProducts) {
        this.jTableProducts = jTableProducts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProducts = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Listar Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jTableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Descripción", "Precio", "Stock"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProducts.setPreferredSize(new java.awt.Dimension(500, 400));
        jScrollPane1.setViewportView(jTableProducts);
        if (jTableProducts.getColumnModel().getColumnCount() > 0) {
            jTableProducts.getColumnModel().getColumn(0).setResizable(false);
            jTableProducts.getColumnModel().getColumn(1).setResizable(false);
            jTableProducts.getColumnModel().getColumn(2).setResizable(false);
            jTableProducts.getColumnModel().getColumn(3).setResizable(false);
            jTableProducts.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProducts;
    // End of variables declaration//GEN-END:variables
}
