package montes.gutierrez.borja.TPV.vistas.productos;

import montes.gutierrez.borja.TPV.vistas.principalFrame.PrincipalFrame;
import java.awt.event.ItemEvent;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import montes.gutierrez.borja.TPV.acciones.productos.EditarProductos;
import montes.gutierrez.borja.TPV.model.Producto;

/**
 * Clase que define el panel para editar un producto.
 *
 * @author Borja Montes Gutiérrez
 */
public class PanelEditarProducto extends javax.swing.JPanel {

    /**
     * Variables
     */
    private EditarProductos editarProductos;

    /**
     * Constructor por defecto.
     *
     * @param frame PrincipalFrame donde se va a dibujar el panel de editar
     * productos.
     */
    public PanelEditarProducto(PrincipalFrame frame) {
        initComponents();
        editarProductos = new EditarProductos(this);
        editarProductos.cargar();
    }

    /**
     * Método para resetear los textos de los campos.
     */
    private void reset() {
        txtStockProduct.setText("");
        txtNameProduct.setText("");
        txtDescriptionProduct.setText("");
        txtPriceProduct.setText("");
    }

    /**
     * Getter del JComboBox con los productos.
     *
     * @return cmbProducts.
     */
    public JComboBox getCmbProducts() {
        return cmbProducts;
    }

    /**
     * Getter del JTextField del código del producto.
     *
     * @return txtCodeProduct.
     */
    public JTextField getTxtCodeProduct() {
        return txtCodeProduct;
    }

    /**
     * Getter del JTextField descropción del producto.
     *
     * @return txtDescriptionProduct.
     */
    public JTextField getTxtDescriptionProduct() {
        return txtDescriptionProduct;
    }

    /**
     * Getter del JTextField del nombre del producto.
     *
     * @return txtNameProduct.
     */
    public JTextField getTxtNameProduct() {
        return txtNameProduct;
    }

    /**
     * Getter del JTextField del precio del producto.
     *
     * @return txtPriceProduct.
     */
    public JTextField getTxtPriceProduct() {
        return txtPriceProduct;
    }

    /**
     * Getter del JTextField del stock del producto.
     *
     * @return txtStockProduct.
     */
    public JTextField getTxtStockProduct() {
        return txtStockProduct;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings(value = "unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCodeProduct = new javax.swing.JLabel();
        txtCodeProduct = new javax.swing.JTextField();
        lbNameProduct = new javax.swing.JLabel();
        txtNameProduct = new javax.swing.JTextField();
        lbDescriptionProduct = new javax.swing.JLabel();
        txtDescriptionProduct = new javax.swing.JTextField();
        lbPriceProduct = new javax.swing.JLabel();
        txtPriceProduct = new javax.swing.JTextField();
        lbStockProduct = new javax.swing.JLabel();
        txtStockProduct = new javax.swing.JTextField();
        cmbProducts = new javax.swing.JComboBox<>();
        lbseleccion = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Panel Editar Producto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        setPreferredSize(new java.awt.Dimension(500, 400));

        lbCodeProduct.setText("Id:");

        txtCodeProduct.setEditable(false);

        lbNameProduct.setText("Nombre:");

        lbDescriptionProduct.setText("Descripción");

        lbPriceProduct.setText("Precio");

        lbStockProduct.setText("Stock");

        cmbProducts.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProductsItemStateChanged(evt);
            }
        });

        lbseleccion.setText("Selecciona producto:");

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbseleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                    .addComponent(lbCodeProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPriceProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbStockProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbNameProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDescriptionProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cmbProducts, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescriptionProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNameProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPriceProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtStockProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodeProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbseleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodeProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNameProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescriptionProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescriptionProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriceProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbStockProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStockProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProductsItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Producto producto = (Producto) cmbProducts.getSelectedItem();
            txtCodeProduct.setText("" + producto.getCodeProduct());
            txtNameProduct.setText(producto.getNameProduct());
            txtDescriptionProduct.setText(producto.getDescriptionProduct());
            txtPriceProduct.setText(producto.getPriceProduct());
            txtStockProduct.setText(producto.getStockProduct());

        }
    }//GEN-LAST:event_cmbProductsItemStateChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        editarProductos.update();
        reset();
        JOptionPane.showMessageDialog(this, "Producto editado");
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbProducts;
    private javax.swing.JLabel lbCodeProduct;
    private javax.swing.JLabel lbDescriptionProduct;
    private javax.swing.JLabel lbNameProduct;
    private javax.swing.JLabel lbPriceProduct;
    private javax.swing.JLabel lbStockProduct;
    private javax.swing.JLabel lbseleccion;
    private javax.swing.JTextField txtCodeProduct;
    private javax.swing.JTextField txtDescriptionProduct;
    private javax.swing.JTextField txtNameProduct;
    private javax.swing.JTextField txtPriceProduct;
    private javax.swing.JTextField txtStockProduct;
    // End of variables declaration//GEN-END:variables
}
